#!/usr/bin/env node
// 构建与一致性校验：
//  - terser 压缩 Env.js → Env.min.js
//  - 将 Env.min.js 内嵌进 box/chavy.boxjs.js 的 Env 段
//  - 将 scripts/sha256.mjs 压缩后内联进 box/chavy.boxjs.js
//  - 注入 box/chavy.boxjs.html 的 SHA-256 到 $.htmlHash
//  - 由 box/chavy.boxjs.js 生成镜像文件 chavy.box.js（头部标记 generated）
// 用法: node scripts/build.mjs [--check]
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { minify } from 'terser'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')

const APP = path.join(ROOT, 'box', 'chavy.boxjs.js')
const MIRROR = path.join(ROOT, 'chavy.box.js')
const ENV_SRC = path.join(ROOT, 'Env.js')
const ENV_MIN = path.join(ROOT, 'Env.min.js')
const HTML = path.join(ROOT, 'box', 'chavy.boxjs.html')
const SHA_SRC = path.join(ROOT, 'scripts', 'sha256.mjs')

const MIRROR_HEADER = '// Generated by scripts/build.mjs - DO NOT EDIT\n'
const SHA_BEGIN = '// SRI_SHA256_BEGIN'
const SHA_END = '// SRI_SHA256_END'

async function minifySrc(src) {
  const { code } = await minify(src, { compress: true, mangle: true })
  if (code == null) throw new Error('terser 输出为空')
  return code
}

async function compute() {
  const envMin = (await minifySrc(fs.readFileSync(ENV_SRC, 'utf8'))).trimEnd()
  const shaMin = (
    await minifySrc(fs.readFileSync(SHA_SRC, 'utf8'))
  )
    .trim()
    .replace(/^export\s+/, '')
  const shaBlock = `${SHA_BEGIN}\n${shaMin}\n${SHA_END}`
  const htmlHash = createHash('sha256')
    .update(fs.readFileSync(HTML))
    .digest('hex')
  const sriBlock = `// SRI_BEGIN\n$.htmlHash = '${htmlHash}'\n${shaBlock}\n// SRI_END`

  let app = fs.readFileSync(APP, 'utf8')
  // 归一化头部: 移除旧区域/残留哈希行/多余空行后, 统一重新插入
  app = app.replace(/\/\/ SRI_BEGIN[\s\S]*?\/\/ SRI_END/, '')
  app = app.replace(/^\$\.htmlHash = '[0-9a-f]{64}'$/gm, '')
  app = app.replace(/\n{3,}/g, '\n\n')
  app = app.replace(
    /^(\$\.versionType = '[^']*')$/m,
    `$1\n${sriBlock}`
  )

  const idx = app.lastIndexOf('function Env(')
  if (idx === -1) throw new Error('box/chavy.boxjs.js 中未找到内嵌 Env 段')
  app = app.slice(0, idx) + envMin + '\n'

  return { envMin, app, mirror: MIRROR_HEADER + app, htmlHash }
}

async function main() {
  const { envMin, app, mirror, htmlHash } = await compute()
  console.log(`SRI htmlHash: ${htmlHash}`)

  const failures = []
  const curEnv = fs.readFileSync(ENV_MIN, 'utf8').trimEnd()
  const curApp = fs.readFileSync(APP, 'utf8')
  const curMirror = fs.readFileSync(MIRROR, 'utf8')
  if (curEnv !== envMin) failures.push('Env.min.js 与 terser 输出不一致')
  if (curApp !== app) {
    const d = firstDiff(curApp, app)
    failures.push(
      `box/chavy.boxjs.js 与构建产物不一致 (首个差异 @${d.i}):\n  CUR: ${JSON.stringify(d.a)}\n  EXP: ${JSON.stringify(d.b)}`
    )
  }
  if (curMirror !== mirror) {
    const d = firstDiff(curMirror, mirror)
    failures.push(
      `chavy.box.js 不是最新生成镜像 (首个差异 @${d.i}):\n  CUR: ${JSON.stringify(d.a)}\n  EXP: ${JSON.stringify(d.b)}`
    )
  }

  if (CHECK) {
    if (failures.length) {
      console.error('一致性校验失败:\n' + failures.join('\n'))
      process.exit(1)
    }
    console.log('一致性校验通过: Env.min.js / box/chavy.boxjs.js / chavy.box.js / SRI 哈希 全部一致')
    return
  }

  if (failures.length) console.warn('注意:\n' + failures.join('\n'))
  fs.writeFileSync(ENV_MIN, envMin)
  fs.writeFileSync(APP, app)
  fs.writeFileSync(MIRROR, mirror)
  console.log('构建完成: Env.min.js / box/chavy.boxjs.js / chavy.box.js 已同步')
}

function firstDiff(a, b) {
  let i = 0
  while (i < Math.min(a.length, b.length) && a[i] === b[i]) i++
  return {
    i,
    a: a.slice(Math.max(0, i - 60), i + 100),
    b: b.slice(Math.max(0, i - 60), i + 100)
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
